name: Deploy

on: [push]

jobs:
  deploy:
    name: Deploy my app

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: chrnorm/deployment-action@v2

      - name: Create GitHub deployment
        if: "contains(github.ref, 'master')"
        id: deployment
        with:
          token: '${{ github.token }}'
          environment: Production

      - name: Create GitHub deployment
        if: "!contains(github.ref, 'master')"
        id: deployment testing
        with:
          token: '${{ github.token }}'
          environment: Testing

      - name: Deploy my app
        run: |
          # add your deployment code here

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'success'

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'failure'
