name: Deploy

on: [push]

jobs:
  build:
    name: Deploy my production app
    runs-on: ubuntu-latest
    
  deploy_to_production:
    steps:
      - uses: actions/checkout@v1

      - if: "contains(github.ref, 'master')"
        uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment: Production

      - name: Deploy my app
        run: |
          # add your deployment code here

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'success'

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'failure'

  deploy_to_test:
    steps:
      - uses: actions/checkout@v1

      - uses: chrnorm/deployment-action@v2

      - if: "!contains(github.ref, 'master')"
        uses: chrnorm/deployment-action@v2
        name: Create GitHub testing deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment: Production

      - name: Deploy my app
        run: |
          # add your deployment code here

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'success'

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'failure'
